### ISSUE TITLE
How to prove a directory or an image file using node SDK

### ISSUE THREAD

**Issue by perdona** [SouthbankSoftware/proofable#18]
I'm trying to use the node SDK to prove a directory or an image file, but I can't seem to find any example of how to achieve this.

**Comment by guiguan** [comment]
Hi @perdona, I just created an [example](https://github.com/SouthbankSoftware/proofable/blob/master/node_sdk/src/examples/typescript_fs.ts) (in TypeScript) for you to use Proofable to prove a directory (`src/examples`). If you clone this repo and run:

```zsh
cd node_sdk
npm i
npm run example-fs
```

You should be able to see the following result:
<img width="803" alt="Screen Shot 2020-11-13 at 5 37 35 pm" src="https://user-images.githubusercontent.com/940189/99037198-5b9acc80-25d7-11eb-9a96-b91b73ce4d57.png">

**Comment by guiguan** [comment]
After you run the above commands, there will also be a Graphviz Dot Graph (`mydir.proofable.dot`) of your proof generated in your current working directory. You can use a viewer such as [this](https://marketplace.visualstudio.com/items?itemName=EFanZh.graphviz-preview) to view it:

<img width="1302" alt="Screen Shot 2020-11-13 at 5 47 06 pm" src="https://user-images.githubusercontent.com/940189/99037914-cac4f080-25d8-11eb-838a-161a4810c639.png">

**Comment by perdona** [comment]
@guiguan Thanks a lot for the rapid response! Will test this asap and post feedback here!
Thanks again!

**Comment by perdona** [comment]
Works perfectly, guys! Thanks a lot!

**Comment by perdona** [comment]
Guys, I'm trying to implement a document verification using proofable node sdk.
Is there a way to implement a incremental way of hashing a directory, meaning that root and previous proofs are immutable?

**Comment by guiguan** [comment]
@perdona yes, the proof (trie) itself is immutable, e.g. whenever you modify an existing trie with [`setTrieKeyValues`](https://docs.proofable.io/node_sdk/reference/classes/_index_.apiclient.html#settriekeyvalues), a new trie with a new root will be returned, which is built incrementally on top of your old trie. Only modified nodes of the old trie are cloned, other nodes will be shared across the old and new tries. You can still access the old trie with the old root.

For a directory, you can build an initial trie with few key-values, then use `setTrieKeyValues`s to push more key-values in as a way to build the trie incrementally.

**Comment by perdona** [comment]
@guiguan Right! So to modify an existing trie, I should use the `.proofable` exported previously? And which method should I use to proof again new pushed keyvalues? (I'm sorry about posting a lot here)

**Comment by guiguan** [comment]
@perdona yes, for now:

1. import your existing trie (`.proofable`) with [`importTrie`](https://docs.proofable.io/node_sdk/reference/classes/_index_.apiclient.html#importtrie)
2. add/update/delete key values with [`setTrieKeyValues`](https://docs.proofable.io/node_sdk/reference/classes/_index_.apiclient.html#settriekeyvalues), which will give you the new root
3. create a proof for the new trie with the new root using [`createTrieProof`](https://docs.proofable.io/node_sdk/reference/classes/_index_.apiclient.html#createtrieproof)
4. you can use [`subscribeTrieProof`](https://docs.proofable.io/node_sdk/reference/classes/_index_.apiclient.html#subscribetrieproof) to wait for the new proof to be confirmed. [Here](https://docs.proofable.io/node_sdk/typescript_example.html#step-5-create-a-proof-for-the-key-values) is an example
5. export the new trie which contains everything with [`exportTrie`](https://docs.proofable.io/node_sdk/reference/classes/_index_.apiclient.html#exporttrie)

After you import the existing trie, you can also use APIs like [`createkeyvaluesproof`](https://docs.proofable.io/node_sdk/reference/classes/_index_.apiclient.html#createkeyvaluesproof) to create a proof for a subset of the key-values, and later on, you can use [`verifyKeyValuesProof`](https://docs.proofable.io/node_sdk/reference/classes/_index_.apiclient.html#verifykeyvaluesproof) to verify them independently.

We are also working on a cloud trie, where we store the trie in Proofable cloud for you and you don't have to keep importing and exporting proofs from time to time.

**Comment by perdona** [comment]
Thanks a lot @guiguan !
